<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaixaFluxo.Infrastructure\CaixaFluxo.Infrastructure.csproj" />
    <ProjectReference Include="..\CaixaFluxo.Application\CaixaFluxo.Application.csproj" />
  </ItemGroup>

</Project>
